[global]
developmentMode = false

[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2e8b57"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"


# .streamlit/config.toml

[app]
title = "Sports Dashboard"
default_timezone = "US/Eastern"
cache_duration = 300
